# exposes the DVWA deployment as a network service
apiVersion: v1  # specifies the API version for the Service resource
kind: Service  # specifies type of resource
metadata:
  name: dvwa-service
spec:
  selector:
    app: dvwa  # matches pods with this label so the service knows which pods to route traffic to
  ports:
  - protocol: TCP  # protocol used for the port mapping
    port: 80  # port the service listens on
    targetPort: 80  # port on the pod to forward traffic to
  type: NodePort  # exposes the service on each node's IP at a static port, making it accessible from outside the cluster

# kubectl apply -f labs/dvwa/deployment.yaml
# kubectl apply -f labs/dvwa/service.yaml
# kubectl get pods
# minikube service dvwa-service --url

# kubectl delete -f labs/dvwa/deployment.yaml
# kubectl delete -f labs/dvwa/service.yaml