# Permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberange-backend
rules:  # Defines what actions the service account can perform on which resources (pods, services, nodes).
  # Create and delete lab pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list"]
  # Create and delete NodePort services per lab session
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list"]
  # Read node IPs to build lab URLs
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
