# Permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberange-backend
rules:  # Defines what actions the service account can perform on which resources (pods, services, nodes).
  # Create and delete lab pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list"]
  # Create and delete LoadBalancer services per lab session, and poll for ingress IP assignment
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list"]
