# Account to apply permissions to.
apiVersion: v1
kind: ServiceAccount  # Define like a user account but for a pod. Gives the pod an identity. Used for RBAC permissions.
metadata:
  name: kuberange-backend
  namespace: default
